name: Run OTP Sender

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # hourly run, change as needed

jobs:
  run-otp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
